### ISSUE TITLE
Getting error as if device is not connected, but it is

### ISSUE THREAD

**Issue by kirklan97** [codedstructure/pylibftdi#11]
Giving the serial number of FTDI device, I get an error as if the device is not found, but using list_devices it is seen, not sure why I cannot access it.

**A10MPXIB**
Traceback (most recent call last):
  File "/home/qa/kirk-personal/new_als_power.py", line 33, in <module>
    relay = bitbangrelay.FT245R(sernum)
  File "/home/qa/kirk-personal/bitbangrelay.py", line 19, in __init__
    self.bb=BitBangDevice(relay_port)
  File "/home/qa/.local/lib/python3.10/site-packages/pylibftdi/bitbang.py", line 69, in __init__
    self.open()
  File "/home/qa/.local/lib/python3.10/site-packages/pylibftdi/bitbang.py", line 75, in open
    super().open()
  File "/home/qa/.local/lib/python3.10/site-packages/pylibftdi/device.py", line 273, in open
    raise FtdiError(msg)
pylibftdi._base.FtdiError: b'device not found' (-3)

No device matching the given specification could be found.
Is the device connected?

Try running the following command to see if the device is listed:

    python3 -m pylibftdi.examples.list_devices

python3 -m pylibftdi.examples.list_devices
FTDI:FT232R USB UART:B001AS67
FTDI:FT245R USB FIFO:A10MPOV9
FTDI:FT232R USB UART:B001BQ9X
FTDI:FT245R USB FIFO:**A10MPXIB**
FTDI:FT232R USB UART:B001BCWY
FTDI:FT245R USB FIFO:A10MQCAT
FTDI:FT232R USB UART:B001AWI0
FTDI:FT245R USB FIFO:A10MPMQ6
FTDI:FT232R USB UART:B001BSM4

**Comment by codedstructure** [comment]
Sorry I didn't see this issue till now :(

If it's still an issue, can you provide the output of the `lsusb` command (assuming you're on Linux?) please, as well as `python3 -m pylibftdi.examples.info`

Does this apply to all your devices when given the appropriate serial number?
